version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn django_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - static_volume:/home/src/app/django_app/staticfiles
        - media_volume:/home/src/app/django_app/mediafiles
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres
    #volumes:
    #     - /Users/etholee/Programming/django_docker/pgdata:/var/lib/postgresql/data
    volumes:
      #- ./site_data/postgres/prod:/var/lib/postgresql/data
      - django_pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env.db
  nginx:
    build: ./nginx
    volumes: 
      - static_volume:/home/src/app/django_app/staticfiles
      - media_volume:/home/src/app/django_app/mediafiles
      - ./logs/nginx:/var/log/nginx
    ports: 
      - 1337:80
    depends_on: 
      - web

volumes:
  django_pg:
  static_volume:
  media_volume: